

# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - ‘*’
  push:
    branches:
      - develop
      - master
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BC_API_URL: https://www.stage.bridgecrew.cloud/api/v1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Scan IaC directory
      id: Bridgecrew-directory-scanner
      uses: bridgecrewio/bridgecrew-action@master
      with:
        directory: "terraform"
        soft-fail: "true"
    - name: Scan IaC file
      id: Bridgecrew-file-scanner
      uses: bridgecrewio/bridgecrew-action@master
      with:
        file: "./terraform/db-app.tf"
        output: "json"
        api-key: ${{ secrets.BRIDGECREW_API_KEY }}
 
